name: Build, Deploy Docker Image
run-name: Build, Deploy Image
on: [push]
env:
  IMAGE_NAME: "nginx-test"
jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Image
        run: docker build -t $IMAGE_NAME .
      - name: List Image
        run: docker images
      - name: Login to GitHub Registry
        run: echo ${{ secrets.TOKEN_GITHUB }} | docker login ghcr.io -u deadyiss --password-stdin
      - name: Push Image
        run: docker push $IMAGE_NAME
      - name: stop and remove existing container
        run: docker-compose down --rmi all
      - name: start container
        run: docker-compose up -d
      - name: view container
        run: docker-compose ps
      - name: check container
        run: curl localhost:80
