name: Build, Deploy Docker Image
run-name: Build, Deploy Image
on: [push]
env:
  IMAGE_NAME: "simple-test"
jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Image
        run: docker build -t $IMAGE_NAME .
      - name: List Image
        run: docker images

  deploy:
    needs: build-push-image
    runs-on: ubuntu-latest
    steps:
      - name: stop and remove existing container
        run: docker-compose down --rmi all
      - name: start container
        run: docker-compose up -d
      - name: view container
        run: docker-compose ps
      - name: check container
        run: curl localhost:80
